### ISSUE TITLE
Crash when trying to save a downloaded episode file

### ISSUE THREAD

**Issue by naim5am** [arma7x/PodKast#1]
Hello,
Thanks for this. I tried to download an episode from one of the podcasts I'm subscribed to, it crashed when download completed. I'm using a Nokia 2720, KaiOS 2.5.2. Rooted,

**Comment by arma7x** [comment]
Can you share podcast title & no. of episode ?

**Comment by naim5am** [comment]
> Can you share podcast title & no. of episode ?

The Trojan Horse Affair. 2nd and 3rd episodes. I didn't try more.

**Comment by arma7x** [comment]
Fixed, https://github.com/arma7x/PodKast/commit/5dd3086e626d03b56fbb35450a35de55d32a6186. Please test & give feedback

**Comment by naim5am** [comment]
I confirm it works. Downloaded episode plays just fine in airplane mode. thanks.
